### PR TITLE
fix message sending if board is empty #118

### LINKED ISSUE #118: Don't send an empty message to Discord if the leader/loser board is empty
See [HandleCheckedLeaderboard](https://github.com/connorkuehl/popple/blob/ee9a9e61ed03bf45bb7eb955398154b0da849e9f/cmd/popplebot/internal/service/service.go#L70) and [HandleCheckedLoserboard](https://github.com/connorkuehl/popple/blob/ee9a9e61ed03bf45bb7eb955398154b0da849e9f/cmd/popplebot/internal/service/service.go#L81).

Both of them unconditionally apply the board template and whisk it off to Discord without first checking if rsp.Board is empty.

---

This bug is fixed if [this test](https://github.com/connorkuehl/popple/blob/72cf77bee05a26dee02d00482c2cf763af801eff/cmd/popplebot/internal/service/service_test.go#L14) and [this test](https://github.com/connorkuehl/popple/blob/72cf77bee05a26dee02d00482c2cf763af801eff/cmd/popplebot/internal/service/service_test.go#L45) are passing once the calls to `t.Skip()` are removed.

### PR DESCRIPTION
**Pull request by rostikts**
closes #118

### CODE REVIEW

**Review by connorkuehl — CHANGES_REQUESTED** [review]
@rostikts Thanks for the patch! Instead of checking the length of the string builder after applying the template, would you mind checking `len(rsp.Board)` at the beginning of the functions instead?

**Comment by rostikts** [comment]
@connorkuehl hi, thanks. Yeah, I've missed this possibility. Fixed :)

**Comment by rostikts** [comment]
Seems like there's an issue with the lint job. I've created a new issue #125.
@connorkuehl  I'll fix the linter issue in the separate PR and then will return to this one

**Comment by connorkuehl** [comment]
@rostikts I appreciate that! When you go to rebase this PR, please squash your 2 commits into 1. Thanks!

**Review by connorkuehl — APPROVED** [review]
Looks great! Thanks 🙂

**Pull request merged**
