### PR TITLE
Made Packages as private

### LINKED ISSUE #36: Convert all type visibilities to package private
None of these types are exported outside of Popple and therefore, to be consistent, all types should be made package-private.

To do this, just look for functions, types, and constants that start with an uppercase letter and make it a lowercase
letter.﻿

### PR DESCRIPTION
**Pull request by lnarasimhan83**
I'm raising this PR to fix #36 

Please note test cases are failing and I need some help at couple of places, 

=====
1
--- FAIL: TestSetAnnounce (0.02s)
    --- FAIL: TestSetAnnounce/off (0.00s)
        command_test.go:160: expected NoAnnounce=true got false
    --- FAIL: TestSetAnnounce/no (0.00s)
        command_test.go:160: expected NoAnnounce=true got false

2. In Object entity I'm unable to make Name and Karma to lowercase - lots of test cases are failing 
Analysed this issue - I can see "makeScratchDB" creating entities afresh - bascially that should make test cases to pass even with lowercase of name and karma 

Please help this is the first time I'm trying to contribute to opensourcee

### CODE REVIEW

**Comment by connorkuehl** [comment]
Hi, @lnarasimhan83! Thanks for working on this. It looks like GORM, the ORM library that Popple uses for interacting with the sqlite3 database, won't create columns for private fields in models. This wasn't obvious when I was skimming the GORM documentation. The only thing I saw was a paragraph on [Field-Level Permission](https://gorm.io/docs/models.html#Field-Level-Permission), which said:

> **Exported fields have all permission** when doing CRUD with GORM, and GORM allows you to change the field-level permission with tag, so you can make a field to be read-only, write-only, **create-only**, update-only or ignored

Emphasis mine. This suggests to me that an unannotated, private field in a GORM model simply won't be created since GORM assumes it doesn't have permission to do so.

I tested this by commenting out the `os.Remove` call in the scratchDB cleanup closure:

```diff
diff --git a/command_test.go b/command_test.go
index 9e05532..b451319 100644
--- a/command_test.go
+++ b/command_test.go
@@ -524,7 +524,7 @@ func makeScratchDB(t *testing.T) (*gorm.DB, func()) {
        _ = db.AutoMigrate(&entity{}, &config{})
 
        return db, func() {
-               os.Remove(dbName)
+               //os.Remove(dbName)
        }
 }
```

and then I ran the failing test:

```console
$ go test -test.run TestSetAnnounce
```

and inspected one of the sqlite databases left behind in the `test-fixtures/` folder.

```console
$ sqlite3 test-fixtures/db005164817
sqlite> .schema configs
CREATE TABLE `configs` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,PRIMARY KEY (`id`));
```

I noticed that the `no_announce` and `guild_id` columns were missing. Here's what that table looks like before your patch:

```console
sqlite> .schema configs
CREATE TABLE `configs` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`guild_id` text,`no_announce` numeric,PRIMARY KEY (`id`));
```

I added a public field to the `config` struct just to test this hypothesis:

```diff
diff --git a/config.go b/config.go
index d53c73e..11f0882 100644
--- a/config.go
+++ b/config.go
@@ -9,6 +9,7 @@ import "github.com/jinzhu/gorm"
 // announce state in Server B.
 type config struct {
        gorm.Model
-       guildID    string
-       noAnnounce bool
+       guildID     string
+       noAnnounce  bool
+       PublicField bool
 }
 ```
 
 And sure enough, it looks like `PublicField`, the only exported field in that model, was created as a column in the table:

```console
sqlite> .schema configs
CREATE TABLE `configs` (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`public_field` numeric,PRIMARY KEY (`id`));
```

So it looks like for the purposes of your PR, you will either need to leave the fields for the `entity` and `config` structs as public, or you will need to annotate them according to [GORM's field-level permission documentation](https://gorm.io/docs/models.html#Field-Level-Permission).

I think the easiest thing to do here would be to just leave those fields as public.

**Comment by lnarasimhan83** [comment]
thank you @connorkuehl  for the detailed explanation. I have reverted and pushed

Please review and let me know if i have to make any other changes

**Comment by connorkuehl** [comment]
I squashed the commits and merged this pull request manually. Thanks!

To github.com:connorkuehl/popple.git
   c375638..7ff219a  master -> master

**Comment by lnarasimhan83** [comment]
Thank you for the opportunity

**Pull request closed without merging**
