### PR TITLE
Changed all ints used for karma levels 

### LINKED ISSUE #100: Change all ints used for karma levels to int64
The database schema already generates 64-bit ints, but all of the `map[string]int` or `adapter.LeaderboardEntry` don't. These instances should be updated to use int64 instead of int.

### PR DESCRIPTION
**Pull request by RishiKumarRay**
Fixed #100

### CODE REVIEW

**Comment by connorkuehl** [comment]
Hi @RishiKumarRay, thanks for spinning this patch! Please address the compiler errors and then I can merge it.

**Comment by RishiKumarRay** [comment]
@connorkuehl I resolved most of the errors but unable to resolve this one 
karma.go:10:18: invalid operation: levels[s.Name] += s.Karma (mismatched types int64 and int)

**Comment by connorkuehl** [comment]
> @connorkuehl I resolved most of the errors but unable to resolve this one
> karma.go:10:18: invalid operation: levels[s.Name] += s.Karma (mismatched types int64 and int) also i have push some more commits with changes

You'll have to update the Subject struct in internal/parse/parse.go.

**Comment by RishiKumarRay** [comment]
@connorkuehl How can i update that, I didn't get it?

**Comment by connorkuehl** [comment]
```diff
diff --git a/internal/parse/parse.go b/internal/parse/parse.go
index bd478e8..a6bb214 100644
--- a/internal/parse/parse.go
+++ b/internal/parse/parse.go
@@ -7,7 +7,7 @@ import (

 type Subject struct {
        Name  string
-       Karma int
+       Karma int64
 }

 func Subjects(s string) []Subject {
 ```

**Comment by RishiKumarRay** [comment]
@connorkuehl Again its failing , am i getting these errors
internal/parse/parse.go:61:23: cannot use karma (type int) as type int64 in field value
internal/parse/parse.go:79:23: cannot use karma (type int) as type int64 in field value
internal/parse/parse.go:104:11: invalid operation: l.pos >= len(l.input) (mismatched types int64 and int)
internal/parse/parse.go:135:20: invalid operation: idx >= len(l.input) (mismatched types int64 and int)

**Comment by connorkuehl** [comment]
@RishiKumarRay, the spirit of issue #100 is not to change _every_ int  to int64. It's only to change an int to an int64 if it has to do with holding someone's karma level. This requires some careful reading of the source code and understanding of the problem domain that this software is operating in.

The only int in internal/parse/parse.go that needs to change are the ones held in the Subject struct or anything that's assigning an int to the int64 inside the Subject struct.

**Comment by connorkuehl** [comment]
Superseded by commit 033633a8f9254f172e740e5d48dd733c5bfbcb6b

**Pull request closed without merging**
