### PR TITLE
Add default size for parsing subjects

### PR DESCRIPTION
**Pull request by Uttkarsh**

### CODE REVIEW

**Comment by connorkuehl** [comment]
Thanks @Uttkarsh! I am on vacation right now but I will look into
merging this early next week.

**Review by connorkuehl — CHANGES_REQUESTED** [review]
Thanks @Uttkarsh! Please remove the const and just open-code the magic 32 into the `make` invocation. That's the only place `DefaultParseSize` is used and `DefaultParseSize` doesn't really convey much.

**Comment by Uttkarsh** [comment]
Agreed @connorkuehl. Removed `DefaultParseSize` and replaced 32 directly into make invocation.

**Review by connorkuehl — APPROVED** [review]
Thank you! 🙂

**Pull request merged**
